### ISSUE TITLE
Color scheme

### ISSUE THREAD

**Issue by marnovo** [janraasch/tab-ahead#103]
Is there a way to change the color scheme (or whole style) of the `tab-ahead` search box and results panel? Thank you.

**Comment by janraasch** [comment]
Again... I am sorry this question was lying around for so long without an answer. You probably do not care any longer, but, of course you could roll your own build of this extension to style it however you want it to look like.

There might also be extensions that let you inject CSS into Chrome.

It's not part of this extensions API though.

**Comment by marnovo** [comment]
Thanks!
