### ISSUE TITLE
forked and change shortcut in manifest, window not getting focused

### ISSUE THREAD

**Issue by oquirozm** [janraasch/tab-ahead#110]
Hi!

I love the extension. If it wasn't for it I would keep using Opera which includes the feature natively. Anyway, the thing is that the current shortcut (Alt+t) is uncomfortable for me so I forked the repo and changed the shortcut in the manifest.json. It works but the input field of the tab search is not getting focused when popping up.

@janraasch I would love if you could give some insight on where could the problem be. I supposed is something inside the `popup.coffee` file but I honestly didn't wanted to go through the whole code to understand where could be the problem. I've never developed extensions before so I'm also a bit out of water here.

Thanks in advance!

**Comment by janraasch** [comment]
Hi Omar,

you do not need to fork the repo simply to change the shortcut. Chrome provides this functionality out of the box:

> Go to `chrome://extensions` and click `Keyboard shortcuts`/`Configure Commands` to change or remove the default shortcut.

See https://github.com/janraasch/tab-ahead#keyboard-shortcut.

Thank you for your kind feedback,
Jan

**Comment by oquirozm** [comment]
Hi Jan,
Thanks for the answer! For some reason I can't see that option but because I'm using the material view for the extensions window. But I'll look for a workaround to this.

Thanks!
