### ISSUE TITLE
Display the number of tabs

### ISSUE THREAD

**Issue by dandv** [janraasch/tab-ahead#12]
Super simple, code at https://github.com/asafh/chrome-tabcounter. Would help us need one less extension. Quite a few users have requested this feature on the [Chrome web store reviews](https://chrome.google.com/webstore/detail/tab-ahead/naoajjeoiblmpegfelhkapanmmaaghmi/reviews) page.

**Comment by janraasch** [comment]
Closing this as there has not been any action here in eight months.
