### ISSUE TITLE
New releases and roadmap

### ISSUE THREAD

**Issue by marnovo** [janraasch/tab-ahead#126]
Hi @janraasch, I've noticed the project is still being worked on, so can we consider it is still maintained? I am curious if/when you plan new public releases and what's the roadmap/upcoming features/fixes. If so, would be nice to have it in the README. Thanks!

**Comment by janraasch** [comment]
Hi @marnovo, I am maintaining this in my free time. 

Feature requests and bugfixes are all handled through GitHub issues. So you should be able to get a good idea of what has been going on by looking at the (closed) issues. 

But in short, there is nothing **I personally** have planned here at the moment. The extension serves its purpose well as it is.

Do you have anything in particular in mind?

**Comment by janraasch** [comment]
If you look at the last few commits, those were really just dependency updates, actually `devDependencies` to be exact. 

The purpose here is really just to keep the project in a state, where bugfixes or other development *could* be done without one having to work on getting the project set up for a few days first 🤓.

**Comment by marnovo** [comment]
Understood, thanks!
