### ISSUE TITLE
please add sort results options

### ISSUE THREAD

**Issue by mailinglists35** [janraasch/tab-ahead#15]
like:
tab age (youngest/oldest first)
distance from the beginning of title/url (words found more close to the beginning/end shown first)
title have precedence over url or viceversa

**Comment by janraasch** [comment]
Closing this as there has not been any action here in eight months and I believe this is outside the scope of this *simple* extension. There are other options (which are more complex) available on the Chrome Web Store, see https://github.com/janraasch/tab-ahead#alternatives.

**Comment by mailinglists35** [comment]
what is the default sorting logic then?

**Comment by janraasch** [comment]
The order is provided by Chrome's `chrome.tabs.query` API. The list given by `chrome.tabs.query` is then filtered using [fuzzy](http://mattyork.github.io/fuzzy/).

You may want to have a look at the alternative extensions listed in the README, see https://github.com/janraasch/tab-ahead#alternatives? Maybe another extension will better fit your needs.
