### ISSUE TITLE
Speed up drop-down response time

### ISSUE THREAD

**Issue by pshahid** [janraasch/tab-ahead#16]
Currently it feels like the pop-up response time when using the keyboard shortcut is a bit too slow. Is there any way this could be sped up? By the time I hit my shortcut and start typing I have to restart typing due to it not grabbing my initial key strokes. I know, it's a first world problem and I should be more patient, sorry :(

 Love the extension by the way, thanks so much for making it!

**Comment by shakeelmohamed** [comment]
There must be a solution. The popup for the [Stylish](https://chrome.google.com/webstore/detail/stylish/fjnbnpbmkenffdnngjfgmeleoegfcffe) extension appears faster but it seems to have a fade in effect.

Anyways, I'll drop the source code for their [popup.js](https://github.com/JasonBarnabe/stylish-chrome/blob/master/popup.js) and [popup.html](https://github.com/JasonBarnabe/stylish-chrome/blob/master/popup.html)

**Comment by janraasch** [comment]
Thanks, @shakeelmohamed. Just for reference, what version of Chrome are you running and what operating system are you running this on?

**Comment by shakeelmohamed** [comment]
OS X 10.9.4/10.9.5 and latests Chrome I guess: Version 42.0.2311.135 (64-bit)

**Comment by shakeelmohamed** [comment]
I think there must be a way to do this. I found this extension called [Vimium](https://github.com/philc/vimium) that has an instant HUD-like search box (similar to Alfred on Mac) when you type shift+T on a page, which will fuzzy search your open tabs in multiple windows then typing enter will go there. This box also handles searches as requested in #17 

The relevant code seems to be here: https://github.com/philc/vimium/tree/master/pages

**Comment by janraasch** [comment]
@shakeelmohamed I just released `v1.2.0` to the Chrome Web Store (https://chrome.google.com/webstore/detail/tab-ahead/naoajjeoiblmpegfelhkapanmmaaghmi). In that version the `.css` file size was reduced *by two thirds*. Maybe that helps with the drop-down response time.

**Comment by shakeelmohamed** [comment]
@janraasch it does seem a bit faster, but not by much. I think the slowness is due to how Chrome is setup for the popup. 
Vimium handles it in a totally different way, see the screenshot. I'm just sharing another solution, not trying to hate on your work here :+1: 

<img width="1375" alt="capturfiles_32" src="https://cloud.githubusercontent.com/assets/1480063/9016892/6fcfa55a-3789-11e5-8d77-a4bf2820bebd.png">

**Comment by janraasch** [comment]
> I think the slowness is due to how Chrome is setup for the popup. 

@shakeelmohamed I think you are correct. I will thus close this issue. Using Vimium is a viable option/alternative and I did put a link to Vimium on the [README Alernatives Section](https://github.com/janraasch/tab-ahead/blob/master/README.md#alternatives) of this repository.

Thank you for contributing.

**Comment by janraasch** [comment]
Good news. I finally found a way to speed things up. In case you are interested, this little commit 96971fc99a7e2b51b3c9914a2757ebdef179f2ee did the trick. 

Try out `v1.2.1` which is now available on the [Chrome Web Store](https://chrome.google.com/webstore/detail/tab-ahead/naoajjeoiblmpegfelhkapanmmaaghmi).

**Comment by pshahid** [comment]
Holy crap, that's funny. Well done!
