### ISSUE TITLE
Port this extension to the new Chromium-based Microsoft Edge browser

### ISSUE THREAD

**Issue by alexdresko** [janraasch/tab-ahead#182]
I wish this extension was available on the new Chromium-based Edge browser that just came out. 

https://www.microsoft.com/en-us/edge?form=MO12GC&OCID=MO12GC

**Comment by alexdresko** [comment]
I just kinda stumbled across [this doc](https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/porting-chrome-extensions). Seems relevant, but I didn't read very much of it.

**Comment by janraasch** [comment]
To be honest, I don't currently have a Windows laptop I available where I could even test this. And, even more honest 😅😇, I personally do not use that browser. 

I will definitely try to help you out, if you or somebody else from the community decides to port the code.

**Comment by alexdresko** [comment]
If you'll accept a pull request, I might be able to dedicate a little time to the effort. Surely it can't be that hard (he says knowing full well that those words have bitten him a thousand times before).

**Comment by janraasch** [comment]
Give it a go, but at the moment I don't think it's feasible for us to go with pinned versions. That will get a lot easier once we're in the monorepo (frontend/web) and have automatic releases, when updates of the chore modules are released. A move to frontend/web is on the way, but it will take some more time.

**Comment by alexdresko** [comment]
Decision: The [Microsoft Edge Extension Toolkit](https://www.microsoft.com/en-us/p/microsoft-edge-extension-toolkit/9nblggh4txvb?rtc=1&activetab=pivot:overviewtab) suggests that the `background` element in `manifest.json` is missing a `persistent` value. 

![image](https://user-images.githubusercontent.com/333022/72806871-19596680-3c24-11ea-9efc-7d2040c01eb7.png)

See more about the persistent flag [here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/background). 

![image](https://user-images.githubusercontent.com/333022/72806907-2c6c3680-3c24-11ea-8148-86e18d2f1293.png)

Thoughts?

**Comment by janraasch** [comment]
Hi, I totally misread your last to latest comment. Context switching is hard...

I think it's cool, that you want to port this 👌.

Now to your question about `persistent`:

For Chrome I really just added the `bg.html` to trick the browser into opening the pop-up faster, see https://github.com/janraasch/tab-ahead/commit/96971fc99a7e2b51b3c9914a2757ebdef179f2ee#diff-34411a66d15db35f42a3ce4d9e5f05db.

So actually you could try removing the `background`-attribute for IE. Maybe it then just works anyway.

**Comment by janraasch** [comment]
Hi @alexdresko, did you make any progress here? #justChecking 😇 😊

PS:

Nice profile picture 😆 😛 😉.

**Comment by janraasch** [comment]
Hi @alexdresko, good news: I ported this puppy to Firefox just now. **Next up:** MICROSOFT EDGE 🎸 😜 .

**Comment by janraasch** [comment]
**FYI** If you enable `Allow extensions from other stores` on `edge://extensions` you can install the extension right away from the Chrome Web Store, i.e. https://chrome.google.com/webstore/detail/tab-ahead/naoajjeoiblmpegfelhkapanmmaaghmi
