### ISSUE TITLE
default should be search all windows

### ISSUE THREAD

**Issue by leao-nardo** [janraasch/tab-ahead#238]
not current , because in the current im seeing what is open. .
so allshould be default , so people dont need to think its not working and only some will look in the options to change that
and in the options put to search on incognitos too

**Comment by janraasch** [comment]
Hi @leao-nardo,

thank you for your contribution 🙏.

I am a little on the fence about this / #239.

I know some people commented on the Chrome Web Store's review page, that they did not know how to search through all windows. 

But then I would be worried now, that by changing the implementation we simply turn this problem around 180 degrees, and people will start commenting about how they do not want to search through all windows 🤓.

I'll let it simmer a little bit. The best way to find out might be to simply give it a try, and watch out for review-comments in the days/weeks after the update.

Just to be sure: You are using this on Chrome, right?

Have a good weekend 🍦,
Jan

**Comment by leao-nardo** [comment]
yes im using Chrome. 
dificult to be a problem because search all includes the current too . 
and you could put the box and show the options on the extension page on webstore , so that when a person finds the extension they will know what options have and how to change

**Comment by leao-nardo** [comment]
actually  incognito already work , just tested , it was not searching before for being only in current
