### ISSUE TITLE
Customize shortcut?

### ISSUE THREAD

**Issue by ilearnio** [janraasch/tab-ahead#31]
Just installed your plugin and it's awesome! I was dreaming about such feature in Chrome for so long! :) 

But is there a way to customize shortcut? For example, I use such feature in my code editor (Sublime Text) a lot, and it is cmd+p. And it would be great if I would use same shortcuts in both Chrome and Sublime Text

**Comment by janraasch** [comment]
Hi @ilearnio. Sure, Chrome has this functionality built in.

>  Go to [chrome://extensions](chrome://extensions) and click `Keyboard shortcuts`/`Configure Commands` to change or remove the default shortcut.

See https://github.com/janraasch/tab-ahead/blob/master/README.md#keyboard-shortcut.

**Comment by ilearnio** [comment]
It works! Thank you!
