### ISSUE TITLE
What is the shortcut for OS X?

### ISSUE THREAD

**Issue by matijaSos** [janraasch/tab-ahead#33]
Cmd + T is already reserved for opening a new tab.

**Comment by janraasch** [comment]
Hi @matijaSos. By default it is `Alt + T` on every OS. Also, you may go to `chrome://extensions` and click `Keyboard shortcuts`/`Configure Commands` in the bottom right  to change or remove the default shortcut. (See [readme](https://github.com/janraasch/tab-ahead#keyboard-shortcut).)

**Comment by matijaSos** [comment]
Thanks @janraasch, found it! It was my error, as a long time linux user, I always associate Cmd with Alt, while it's actually Option button.

Maybe you could just add in your description "(Opt + T on Mac)", to help clumsy people such as myself!

**Comment by janraasch** [comment]
It does say

> Keyboard Shortcut:
> Alt+T

on the description on the Chrome Web Store: https://chrome.google.com/webstore/detail/tab-ahead/naoajjeoiblmpegfelhkapanmmaaghmi

**Comment by matijaSos** [comment]
Right, I saw that, I was thinking you could maybe put that just after that part, so it would be then "Alt + T (Opt+T on Mac)". I'm usually using a windows keyboard with my Mac, so Alt is actually Cmd.

But maybe everybody knows Alt is actually Option on Mac, so this is just a silly remark, don't mind it then please!

**Comment by janraasch** [comment]
Ok, I am starting to see your point. I will keep this in mind. On my German Mac keyboard it does say `Alt`, so I was not aware of the difference.
