### ISSUE TITLE
Search in bookmarks

### ISSUE THREAD

**Issue by klaidliadon** [janraasch/tab-ahead#35]
It would be great if the extension allows to search also in bookmarks.

**Comment by janraasch** [comment]
Hi @klaidliadon, thank you for your feedback. This feature is a little bit outside the scope of this extension IMHO. Of course it is technically feasible, but there would be a few questions that would have to be answered, e.g.

1. How many bookmarks to display (as there may be a whole bunch of matching results)?
2. Should there be a fixed ration of bookmark-results to open-tab-results?
3. Most importantly how can this be done visually? There needs to be a way to distinguish open-tab-results from bookmark-results. Should these be different lists? Should they be intertwined?

That being said, I do believe this to blow up the scope of this extension a little too much. If you are looking for an alternative which does already implemented this, please have a look at the [alternatives](https://github.com/janraasch/tab-ahead#alternatives) listed in the readme.

Another option would be to do a *tab ahead* spin-off. Most of the code could be reused to do a *bookmark ahead*-type extension, which does fuzzy searching on bookmarks.

**Comment by janraasch** [comment]
No action on this in more than half a year. I am closing this issue.

In case you still desire this feature, you may want to check out [Quick Tabs](https://chrome.google.com/webstore/detail/quick-tabs/jnjfeinjfmenlddahdjdmgpbokiacbbb).
