### ISSUE TITLE
Show Favicons for matched tabs

### ISSUE THREAD

**Issue by burnedikt** [janraasch/tab-ahead#36]
First things first: Absolutely love this chrome extension. I actually wrote something quite similar just for fun and just stumbled upon Tab Ahead. 

I personally think it would help users to additionally see the favicon for each matched tab. As of right now, you still have to read the title / url of the tab to make sure you found the right one. Sometimes you already know what the favicon looks like so this might speed up the selection / filtering process even more. 

What do you think?

**Comment by janraasch** [comment]
Hi @burnedikt, thank you for your kind feedback. 

In general I think anything that would help a user to find the tab she is looking for faster would be great. However, I do definitely favour a streamlined simple design over a colorful bloated one. 

In short: I am worried that favicons would mess with the simple and clean design of the extension, but I am definitely open to be proven wrong here :).

That being said, in case you are looking for another option with favicons, several of the alternatives mentioned in the [readme](https://github.com/janraasch/tab-ahead/blob/master/README.md) do over this feature, e.g. [Tabbr](https://chrome.google.com/webstore/detail/tabbr-tab-manager/pnlmkddpdkjapnghefahkniilfnodcol), and [TabJuggler](https://chrome.google.com/webstore/detail/tabjuggler/jgiplclhploodgnkcljjgddajfbmafmp/).

**Comment by janraasch** [comment]
No action on this in more than half a year. I am closing this issue.

In case you still need favicons, you may want to check out [Quick Tabs](https://chrome.google.com/webstore/detail/quick-tabs/jnjfeinjfmenlddahdjdmgpbokiacbbb).

**Comment by a-tinsmith** [comment]
Hi! I just tried your extension and it's great! Very fast and slick. However, I would like to revive this feature request. As many of us are visual first and text second, it would be really helpful to see favicons in the list of search results.
Maybe it is possible to make it optional?

**Comment by janraasch** [comment]
Hi @a-tinsmith

>  I just tried your extension and it's great! Very fast and slick. 

Thank you for the kind words 💟 .

> However, I would like to revive this feature request. As many of us are visual first and text second, it would be really helpful to see favicons in the list of search results.
Maybe it is possible to make it optional?

Makin it *optional* could be a way to go.

Not sure about your technical background, but I would be more than happy to review a pr with a first draft implementation.

Cheers 👋🏻 ,
Jan

**Comment by a-tinsmith** [comment]
Thank you for repopening the ticket. My background is software engineering. However, it's mostly backend development. I will lookat the code this Monday to see if I can do this.
