### ISSUE TITLE
Do not mess with my search terms

### ISSUE THREAD

**Issue by thecrazy** [janraasch/tab-ahead#7]
Hi,

I like the addon. Is there a way to prevent it form splitting my search words? I would like to only get hits from complete words.

**Comment by janraasch** [comment]
Closing this as there has not been any action here in eight months.

**Comment by mailinglists35** [comment]
there hasn't been any action, but there is a question i asked that has no answer:

«would it be possible (to be able) to change the background and/or color of fuzzy results so it would be easier to distinguish them?»

**Comment by janraasch** [comment]
Anything is possible, but there is a time constraint as with everything :). For this extension, sadly, this feature will probably not be implemented.

You may want to have a look at the alternative extensions listed in the README, see https://github.com/janraasch/tab-ahead#alternatives? Maybe another extension will better fit your needs.
