### ISSUE TITLE
Tab is not being focussed

### ISSUE THREAD

**Issue by avamsi** [janraasch/tab-ahead#73]
Tab Ahead 1.3.0 on Chrome 51.0, Ubuntu

After switching to a tab in the **same** window using Tab Ahead, I can't use any keyboard shortcuts. For example, I can't close the tab or switch tabs. It's as if no tab is in focus.

FWIW, I don't have this problem when I'm switching to a tab in different window.

**Comment by janraasch** [comment]
Hi @avamsi. Thank you for opening this issue. I am on Mac OS X, where I cannot reproduce this issue (I just tried with `Chrome Version 51.0.2704.103 (64-bit)`), and do not have an Ubuntu machine handy at the moment. So I am afraid it may take a while for this to get fixed unless of course you yourself can debug and maybe issue a pull request. Otherwise I'll see to get a VM with Ubuntu installed and check it out there.

**Comment by avamsi** [comment]
What's weird is that, it works fine for sometime when I restart Chrome. Then, after sometime, it works for some tabs and it doesn't for others and after some more time, I face this issue every time I switch tabs.

I'll test it on my Windows machine and see if it's OS specific.

**Comment by janraasch** [comment]
> I'll test it on my Windows machine and see if it's OS specific.

That might be helpful. Thank you.

**Comment by avamsi** [comment]
Just to let you know, It's working fine on my Windows machine.

**Comment by janraasch** [comment]
Ok. Can you try the beta channel of Chrome to see, if it's maybe related to an issue within Chrome?

**Comment by avamsi** [comment]
I faced this issue on a work computer running Goobuntu. I guess it's possible that some work extensions are interfering with this extension or something.

**Comment by janraasch** [comment]
You are right, another thing you could try is to disable all other plugins and extensions and see if the problem persists.

**Comment by avamsi** [comment]
I can't uninstall extensions installed by "enterprise policy". I'll test it on a non-work Ubuntu machine and let you know. I have a feeling that it'll work fine. :smiley: It'll take a while though.

**Comment by avamsi** [comment]
JTLYK, tried on a Ubuntu machine, worked as expected.
