### ISSUE TITLE
Add option to show all tabs at first when search dialog is opened

### ISSUE THREAD

**Issue by jensjacobt** [janraasch/tab-ahead#8]
Please, add an option to show all tabs at first when search dialog is opened (or even make it default).

I know that pressing `:` (colon) will get since it's in every URL (that I know of). However, this is an extra keypress that should be unnecessary. Also, there is something pedagogical about seeing the results filter as you filter them (when there are only so many).

Thanks for a great extension!

Regards,
Jens Jacob
(My first name is two names.)

**Comment by janraasch** [comment]
Closing this as there has not been any action here in nine months.
