### ISSUE TITLE
popup too far left

### ISSUE THREAD

**Issue by justtoreportbug** [janraasch/tab-ahead#80]
The search popup is left-justified below the icon in Chrome's extension row making it fall off the left-side of the screen in many cases. Should float to be visible always. Workaround is to move the icon to the middle of course but I use Tab Ahead very often, so I prefer it on the left.

**Comment by janraasch** [comment]
Hi @justtoreportbug, thank you for taking the time and signing up to Github *just to report [this] bug*. Could you provide a screenshot of the issue you described?

**Comment by janraasch** [comment]
Closing this as there has not been any action here in over a year.
