### ISSUE TITLE
Tab Preview

### ISSUE THREAD

**Issue by garyemerson** [janraasch/tab-ahead#82]
The proposed behavior is that the selected search result is auto switched to. This is meant to work like a kind of tab preview. The sort of "workflow" I imagine is: you hit the shortcut, type in your query, optionally arrow up/down to find desired tab by using the previews and then hit enter to commit to switching; all without the need to shift focus to the upper right to look at search results. I'm thinking it'd probably make the most sense for this to be used only in "Current Window" mode since auto switching OS windows could be slow and/or annoying to the user.

Benefits:
* Allows faster use bc it's no longer required to read results but instead just recognize page you want to switch to via previews. Personally I can differentiate websites faster by looking at their actual content rather than their title/url.
* More similar to Sublime behavior

Concerns/Drawbacks:
* Might be a performance hit

I'd definitely be willing to work on this but I wanted to gauge interest first.

**Comment by janraasch** [comment]
Hi @garyemerson, sorry for not replying earlier. I think this would certainly need to be prototyped. I have a feeling that the popup will close or lose its JavaScript context, when switching tabs in the background. And even if it does work, we would need to see how it feels/looks from a UI/UX perspective.

I think it might be cool, but it might also be a little too much from a UI perspective. In Sublime the UI from text file to text file is pretty consistent, while web pages might look totally different so switching between them very fast (i.e. while typing/searching) might be overkill to the eye. We would really need to see it to judge this.

**Comment by janraasch** [comment]
Closing this as there has not been any action here in over a year.
