### ISSUE TITLE
new tab if result not found

### ISSUE THREAD

**Issue by bigginhill** [janraasch/tab-ahead#83]
I love this inspired extension. 

I often look for tabs that are not open (but that I tend to have open, e.g. webmail) - is it possible to add an option to open a new tab based on the searched text if it is a url e.g. searching hotmail.com when hotmail is not open would offer the option to open hotmail.com.

Either way, I love tab-ahead.

**Comment by janraasch** [comment]
Thank you for your interest and kind words :)

That could certainly be done I suppose. How exactly would you image this

> e.g. searching hotmail.com when hotmail is not open would offer the option to open hotmail.com.

to work? Or rather: How would you like this "option" to be "offered" by the extension?

**Comment by janraasch** [comment]
Closing this as there has not been any action here in over a year.
