### ISSUE TITLE
Add open tabs count badge

### ISSUE THREAD

**Issue by danbozaru** [janraasch/tab-ahead#84]

**Comment by janraasch** [comment]
I am personally not a big fan of this from a design perspective. If we can make it look good and maybe even make it an optional feature, then I would certainly be open for a pull request.

**Comment by janraasch** [comment]
Closing this as there has not been any action here in over a year.

**Comment by leao-nardo** [comment]
https://chrome.google.com/webstore/detail/session-buddy/edacconmaakjimmfgnblocblbcdcpbko
this other have this option and its optional there , maybe its easy to copy from there. its an useful thing to keep track.
