### ISSUE TITLE
Will not install on Chrome running on Andriod Samsung Tablet

### ISSUE THREAD

**Issue by treahy** [janraasch/tab-ahead#85]
Perhaps I'm doing something wrong, but I browse to:
https://chrome.google.com/webstore/detail/tab-ahead/naoajjeoiblmpegfelhkapanmmaaghmi?hl=en
and tell it to install but it doesn't appear to activate.
Barry

**Comment by janraasch** [comment]
I do not own an Android Samsung Tablet. However, running a quick google search it seems like there is no support for Chrome Extensions on Android:

> Google Chrome for Android will not be getting extension support any time soon, Chrome developers have revealed.

See http://www.omgchrome.com/chrome-android-extensions-not-planned-ama/
and http://www.androidpolice.com/2016/09/08/awesome-can-now-add-chrome-extensions-android-device-desktops-chrome/

So I guess there simply is no support for running Chrome Extensions on Android Chrome.
