### ISSUE TITLE
Upload this to Firefox store

### ISSUE THREAD

**Issue by 3v1n0** [janraasch/tab-ahead#92]
Now that firefox supports web extensions I've tried to load this .crx to https://www.extensiontest.com and...

![immagine](https://user-images.githubusercontent.com/345675/30566415-43dbbc2c-9ccc-11e7-8633-9ea2afd1535a.png)

So, I guess it would be cool if you might hit the upload button to make this cool extension available also to firefox users.

**Comment by janraasch** [comment]
Hi there, thank you for testing this. This is a nice idea, however there are a few things to consider. Maybe you could help me with this as I do not use Firefox much these days.

# Questions

1. Is there a use case for this on FF? (As far as I can see FF's standard address bar already sports a "switch to tab"-feature for open tabs.)

2. If the answer to 1. is yes, then the next question is: Does the UI fit in with FF. There we would definitely need to do some tests to see how this looks and feels.

Most important question is of course the first one. Everything follows from the use case.

**Comment by janraasch** [comment]
Closing this as there has not been any action here in over a year.

**Comment by janraasch** [comment]
**FYI** There we are https://github.com/janraasch/tab-ahead/pull/211 🥰 .

The extension is currently under review by the Firefox team.

Also, see https://github.com/janraasch/tab-ahead/pull/216.
